name: layout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  carousel_slider: ^4.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/img1.jpg
    - assets/img/photo-1.jpg
    - assets/img/159690.png
    - assets/img/desta.jpg
    - assets/img/grade-da-mesa-de-nove-quadrados.png
    - assets/img/reels.png
    - assets/img/marcacao.png
    - assets/img/tailandia.jpg
    - assets/img/laranja.jpg




